//
//  FontHeader.h
//  WeatherFontIcon
//
//  Created by Shaffiulla Khan on 10/28/14.
//  Copyright (c) 2014 Shaffiulla Khan. All rights reserved.
//

#define kWind                           @""
#define kWindSun                        @""
#define kWindMoon                       @""
#define kUpload                         @""
#define kUmbrella                       @""
#define kThermometerFull                @""
#define kThermometerThreeFourth         @""
#define kThermometerOneFourth           @""
#define kThermometerOneSecond           @""
#define kThermometerZero                @""
#define kSunset                         @""
#define kSunrise                        @""
#define kSun                            @""
#define kSnow                           @""
#define kSnowSun                        @""
#define kSnowMoon                       @""
#define kSnowAlt                        @""
#define kSnowAltSun                     @""
#define kSnowAltMoon                    @""
#define kRain                           @""
#define kRainSun                        @""
#define kRainMoon                       @""
#define kRainAlt                        @""
#define kRainAltSun                     @""
#define kRainAltMoon                    @""
#define kMoon                           @""
#define kLightning                      @""
#define kLightningSun                   @""
#define kLightningRain                  @""
#define kLightningRainSun               @""
#define kLightningRainMoon              @""
#define kLightningMoon                  @""
#define kLight                          @""
#define kHurricane                      @""
#define kHail                           @""
#define kHailSun                        @""
#define kHailMoon                       @""
#define kFog                            @""
#define kFogSun                         @""
#define kFogMoon                        @""
#define kDrizzle                        @""
#define kDrizzleSun                     @""
#define kDrizzleMoon                    @""
#define kDrizzleAlt                     @""
#define kDrizzleAltSun                  @""
#define kDrizzleAltMoon                 @""
#define kDownload                       @""
#define kDegreeFarenheit                @""
#define kDegreeCelcius                  @""
#define kCompass                        @""
#define kCompassWest                    @""
#define kCompassSouth                   @""
#define kCompassNorth                   @""
#define kCompassEast                    @""
#define kCloud                          @""
#define kCloudWind                      @""
#define kCloudWindSun                   @""
#define kCloudWindMoon                  @""
#define kCloudSun                       @""
#define kCloudMoon                      @""

#define KFontName                       @"Pe-icon-7-weather"

/*#define FontList                        @{@"wind":kWind,@"wind-sun":kWindSun,@"wind-moon":kWindMoon,@"upload":kUpload,@"umbrella":kUmbrella,@"thermometer-full":kThermometerFull,@"thermometer-3-4":kThermometerThreeFourth,@"thermometer-1-4":kThermometerOneFourth,@"thermometer-1-2":kThermometerOneSecond,@"thermometer-0":kThermometerZero,@"sunset":kSunset,@"sunrise":kSunrise,@"sun":kSun,@"snow":kSnow,@"snow-sun":kSnowAltSun,@"snow-moon":kSnowMoon,@"snow-alt":kSnowAlt,@"snow-alt-sun":kSnowAltSun,@"snow-alt-moon ":kSnowAltMoon,@"rain":kRain,@"rain-sun":kRainSun,@"rain-moon ":kRainMoon,@"rain-alt ":kRainAlt,@"rain-alt-sun":kRainAltSun,@"rain-alt-moon":kRainAltMoon,@"moon":kMoon,@"lightning":kLightning,@"lightning-sun":kLightningSun,@"lightning-rain":kLightningRain,@"lightning-rain-sun":kLightningRainSun,@"lightning-rain-moon":kLightningRainMoon,@"lightning-moon":kLightningMoon,@"light":kLight,@"hurricane":kHurricane,@"hail":kHail,@"hail-sun":kHailSun,@"hail-moon":kHailMoon,@"fog":kFog,@"fog-sun":kFogSun,@"fog-moon":kFogMoon,@"drizzle":kDrizzle,@"drizzle-sun":kDrizzleSun,@"drizzle-moon":kDrizzleMoon,@"drizzle-alt":kDrizzleAlt,@"drizzle-alt-sun":kDrizzleAltSun,@"drizzle-alt-moon":kDrizzleAltMoon,@"download":kDownload,@"degree-farenheit":kDegreeFarenheit,@"degree-celcius":kDegreeCelcius,@"compass":kCompass,@"compass-west":kCompassWest,@"compass-south":kCompassSouth,@"compass-north":kCompassNorth,@"compass-east":kCompassEast,@"cloud":kCloud,@"cloud-wind":kCloudWind,@"cloud-wind-sun":kCloudWindSun,@"cloud-wind-moon":kCloudWindMoon,@"cloud-sun":kCloudSun,@"cloud-moon":kCloudMoon}*/

#define FontList                        @{@"100":kSun,@"101":kCloudWind,@"102":kCloudWind,@"103":kCloudWindSun,@"104":kCloud,@"200":kWind,@"201":kWind,@"202":kWind,@"203":kWind,@"204":kWind,@"205":kWind,@"206":kWind,@"207":kWind,@"208":kWind,@"209":kWind,@"210":kWind,@"211":kHurricane,@"212":kWind,@"213":kWind,@"300":kRain,@"301 ":kRainAlt,@"302":kLightningRain,@"303":kLightningRain,@"304":kHail,@"305":kDrizzleAlt,@"306":kDrizzle,@"307":kRain,@"308":kRain,@"309":kDrizzle,@"310 ":kRainAlt,@"311 ":kRainAlt,@"312 ":kRainAlt,@"313 ":kHail,@"400":kSnow,@"401":kSnowAlt,@"402":kSnowAlt,@"403":kSnowAlt,@"404":kSnowAlt,@"405":kSnowAlt,@"406":kSnowAlt,@"407":kSnowAlt,@"500":kFog,@"501":kFog,@"502":kFog,@"503":kFog,@"504":kFog,@"505":kFog,@"506":kFog,@"507":kFog,@"508":kFog,@"900":kThermometerFull,@"901":kThermometerOneSecond,@"999":kUpload,}